### ISSUE TITLE
comment

### ISSUE THREAD

**Issue by dltmdrbtjd** [sunny-yo/react_week1#1]
- 프로젝트 끝내시느라 고생 많으셨습니다. 😎

- 과제 완료 후에 redux-toolkit으로 slice를 만들어서 구현하는 걸 해봤는데, redux에서만 state를 관리하는 부분은 자료도 많고 docs에도 설명이 순서대로 잘 되어있어서 괜찮았는데, createAsyncThunk로 thunk를 만들고 extraReducers로 action이 어떻게 넘어가는지 찾기가 힘들어서 일일이 확인하면서 어떻게 만들기는 했는데 이게 맞는지 모르겠고, 시간도 조금 오래 걸렸습니다.
실제로는 db와 통신을 할 일도 많을 것 같은데 createAsyncThunk를 어떤 부분/기능을 구현할 때 사용하고, 데이터가 어떻게 흘러가는지(db에서 받아온 이후에 state를 업데이트할 때까지..?) 흐름을 알고 싶습니다.
  - redux-toolkit을 사용하고 계시는군요 ! 만약 기존에 redux를 잘 이해하지않고 사용하신다면 더 헷갈리실수도 있습니다. 우선 createAsyncThunk와 extraReducers로 어떤 순서로 처리되는지 간단하게 설명하자면 이렇습니다. 우선 createAsyncThunk의 변수명을 extraReducer에서 redux-toolkit의 방식으로 넣어주면 감지할 수 있게 되는겁니다.(첫 번째 인자에 타입을 넣어주는걸 잘 생각해보시길 바랍니다) 그 후에 만약 서버에서 books라는 배열을 받아온다고 해보면 api를 통해 받아오고 payload로 감싸서 return시켜줍니다. 그 후에 extraReducers에 action 인자에서 그 값을 받아와서 실제 state에 값을 넣어주게되면 서버에서 받아온 데이터를 store에 저장하는 과정이 끝나게 됩니다.
  - 전체적으로 과제 굉장히 깔끔하게 잘하신것 같아요 전체적인 폴더 구조 및 코드 구조가 아주 좋네요 😄 ! 남은 기간도 화이팅 하시길 바랍니다 

```js
const getBooks = createAsyncThunk('books/GET_BOOK', async () => {
  try {
   const { data } = await apis.GetBooks()
   const payload = { books: data.books }
   return payload;
  } catch (err) {
    console.log(err)
  }
}

// slice
extraReducers: {
  [getBooks.pending.type]: (state) => {
    state.loading = true
  },
  [getBooks.fulfilled.type]: (state,action) => {
    state.books = action.payload.books
    state.loading = false
  },
  [getBooks.rejected.type]: (state) => {
    state.loading = false
  }
}
```

**Comment by sunny-yo** [comment]
오 감사합니다😊
처음에 createAsyncThunk에서 리턴을 하면 extraReducers에서 action.payload로 받을 수 있다는 걸 몰라서 한참 헤맸었는데 예시랑 설명 자세하게 알려주셔서 감사합니다~!
